### ISSUE TITLE
Questions about ssh connection example

### ISSUE THREAD

**Issue by AbdelhakVerwest** [hashicorp/boundary-reference-architecture#10]
Does the target machine need to have the same key as the controller/worker machines? How do I tell Boundry which key to use when it wants to connect to a target machine? Thank you in advance

**Comment by malnick** [comment]
@AbdelhakVerwest - Take a look at the response here that details how this handles provisioning the SSH keys to EC2 instances: https://github.com/hashicorp/boundary-reference-architecture/issues/9#issuecomment-708873402

Let me know if that helps!

**Comment by malnick** [comment]
Closing this out with no response in 7 days.

**Comment by AbdelhakVerwest** [comment]
> @AbdelhakVerwest - Take a look at the response here that details how this handles provisioning the SSH keys to EC2 instances: [#9 (comment)](https://github.com/hashicorp/boundary-reference-architecture/issues/9#issuecomment-708873402)
> 
> Let me know if that helps!

Sorry for the late reply. I saw the example and I tried it out myself. It helped me understand.
Thank you for your time!
