### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by dotancohen81** [hashicorp/boundary-reference-architecture#12]
when trying to init from /deployment

Could not retrieve the list of available versions for provider
localhost/providers/boundary: could not connect to localhost: Failed to
request discovery document: Get
"https://localhost/.well-known/terraform.json": x509: certificate has expired
or is not yet valid: current time 2020-10-17T00:03:01+03:00 is after
2018-06-07T09:01:17Z

**Comment by basanaguk** [comment]
Guess instruction is not clear mentioned on this repo, but you would need to have provider built locally by following instructions mentioned in the boundary prover repo: https://github.com/hashicorp/terraform-provider-boundary.

```
1. Clone the repository
2. Enter the repository directory
3. Build the provider using make dev. This will place the provider onto your system in a Terraform 0.13-compliant manner.
```

**Comment by malnick** [comment]
Yes, this is true. I'll update this to the provider on the registry thank you!
