### ISSUE TITLE
variable boundary_bin is not declared

### ISSUE THREAD

**Issue by basanaguk** [hashicorp/boundary-reference-architecture#13]
While executing command as per the guide:

`terraform apply -target module.aws -var boundary_bin=/usr/bin/boundary
`
will result:
```
Error: Value for undeclared variable

A variable named "boundary_bin" was assigned on the command line, but the root
module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration
```
Guess users are required to create variables.tf locally and declare _boundary_bin_ as per suggestion.

**Comment by malnick** [comment]
Thanks @basanaguk! Let me know if the PR I opened fixes this for you.
