### ISSUE TITLE
Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol status code: 400

### ISSUE THREAD

**Issue by basanaguk** [hashicorp/boundary-reference-architecture#14]
Load balancer module, [lb.tf](https://github.com/hashicorp/boundary-reference-architecture/blob/main/deployment/aws/lb.tf) has been defined with lb target group and stickiness of type: _lb_cookie_ at line 20:

```
  stickiness {
    enabled = false
    type    = "lb_cookie"
}

```
With 
`terraform apply -target module.aws -var boundary_bin=/usr/bin/boundary`

it results in an error:
```
Error: Error modifying Target Group Attributes: InvalidConfigurationRequest: Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol
        status code: 400, request id: 182d1591-765b-********************************
```

Similar to issues reported in [here](https://github.com/terraform-providers/terraform-provider-aws/issues/10494) and [here](https://github.com/ansible/ansible/issues/67993).

As mentioned in those issues, work around is to declare stickiness of type **_source_ip_**

**Comment by malnick** [comment]
Thanks @basanaguk - let me know if the PR I opened for this fixes the issue!

**Comment by basanaguk** [comment]
> Thanks @basanaguk - let me know if the PR I opened for this fixes the issue!

Yep, this will fix! Thanks..
