### ISSUE TITLE
error reading wrappers from "recovery_kms_hcl": Error configuring kms: error fetching AWS KMS wrapping key information: NotFoundException

### ISSUE THREAD

**Issue by basanaguk** [hashicorp/boundary-reference-architecture#15]
While following below step from the deployment README.md
`Configure boundary using terraform apply (without the target flag), this will configure boundary per boundary/main.tf`

Getting 
`Error: error reading wrappers from "recovery_kms_hcl": Error configuring kms: error fetching AWS KMS wrapping key information: NotFoundException: Key 'arn:aws:kms:eu-west-1:*****************:key/0b2ad402-*****-46ac-****-**************' does not exist`

However from previous terraform apply for module.aws I could see, key was created with the given ID but can't find same in portal:
`module.aws.aws_kms_key.recovery: Creation complete after 5s [id=*****-46ac-****-**************]`

**Comment by malnick** [comment]
@basanaguk Make sure the AWS_REGION set in your shell is the same as was used to create the key. I've seen these two regions differ, and as the boundary provider interacts with boundary's underlying KMS plugin system, will need the AWS_REGION to be correct. Double check the region on the arn or the key created and make sure it's the same as what is being called in the not found exception.

**Comment by basanaguk** [comment]
> @basanaguk Make sure the AWS_REGION set in your shell is the same as was used to create the key. I've seen these two regions differ, and as the boundary provider interacts with boundary's underlying KMS plugin system, will need the AWS_REGION to be correct. Double check the region on the arn or the key created and make sure it's the same as what is being called in the not found exception.

Yes, that was the reason! thank you - this solved my issue!
