### ISSUE TITLE
Where to find the sha for https address?

### ISSUE THREAD

**Issue by queglay** [hashicorp/boundary-reference-architecture#23]
In the README it says the address for the UI is located at https://boundary-test-controller-<random_name>-<random_sha>.elb.us-east-1.amazonaws.com:9200

Is there anymore information on where the random_sha is located for the controller?

**Comment by malnick** [comment]
The random sha is created by AWS upon LB creation. You can look it up in the AWS console, or locally in the terraform.tfstate file created for the Terraform output.

**Comment by queglay** [comment]
Thanks Jeff!  Looking forward to talking out for a spin again this weekend.

**Comment by malnick** [comment]
Closing as resolved.
