### ISSUE TITLE
run all -> ERROR: Version in "./docker-compose.yml" is unsupported. 

### ISSUE THREAD

**Issue by biofool** [hashicorp/boundary-reference-architecture#25]
/boundary-reference-architecture/deployment/docker$ ./run all
~/boundary-reference-architecture/deployment/docker/compose ~/boundary-reference-
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false
...

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

$ docker-compose -v
docker-compose version 1.25.0, build unknown

**Comment by malnick** [comment]
Hey there @biofool - looks like you need to upgrade docker-compose to greater than 3 per https://github.com/hashicorp/boundary-reference-architecture/blob/main/deployment/docker/compose/docker-compose.yml#L1

Looks like you're on 1.25. Can you upgrade docker-compose and retry?

**Comment by biofool** [comment]
I looked at that also I think that version # is the file version # as there is no docker-compose version 3.8.  I upgraded compose to 1.27.4 and that did resolve the issue.  Might be worth a comment as 1.27 isn't available in ubuntu 20 yet.
