### ISSUE TITLE
Healthcheck `unhealthy` for boundary container

### ISSUE THREAD

**Issue by mponti** [hashicorp/boundary-reference-architecture#28]
The healthcheck for the boundary container is returning unhealthy because curl is not installed in the container.

For version 0.1.1 and 0.1.2

Returns healthy after running: `docker-compose exec -u root boundary /bin/sh -c "apk add --no-cache curl"`

**Comment by malnick** [comment]
Thanks for raising this @mponti - will get a fix out soon.
