### ISSUE TITLE
Readme clarification on login scope

### ISSUE THREAD

**Issue by mponti** [hashicorp/boundary-reference-architecture#29]
I would suggest adding a note to make sure the selected scope is "primary" for login with the terraform generated usernames.

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/1376009/99586596-902ecf80-29ad-11eb-9ed0-efa29ceb0fbe.png">

also that the scope id is in the URL for the UI portion.

Happy to make the PR if deemed helpful

**Comment by malnick** [comment]
PR's gladly accepted! That example still provisions with generated resources, which can be disabled by setting the appropriate flags in https://github.com/hashicorp/boundary-reference-architecture/blob/main/deployment/aws/aws/install/install.sh#L30
