### ISSUE TITLE
Unable to connect to targets from other machines

### ISSUE THREAD

**Issue by jellevink** [hashicorp/boundary-reference-architecture#31]
Seems like you are only able to connect to the target instances from the machine that has spun up Boundary. Have tried to connect using a different machine and cannot reach targets, this machine has Boundary installed and can successfully authenticate via the CLI and read targets, just not connect. 
 
I have only tried this issue using SSH via the CLI, but suspect that RDP is also unavailable.

**Comment by k4lii** [comment]
Same issue for me i can authenticate my self throught boundary but cant connect
<img width="1005" alt="cli" src="https://user-images.githubusercontent.com/71388385/102509639-0bf06a80-4087-11eb-9caf-c532eddc09cb.PNG">

**Comment by malnick** [comment]
@jellevink - It's likely that the worker config isn't correct for accessing this off host. These references are meant to be examples, I didn't build them to work outside the intended use case of 127.0.0.1. That worker config is where I'd start, probably need to set the worker public IP to have it route correctly.

**Comment by malnick** [comment]
Closing this out since it's been a while with no response.
