### ISSUE TITLE
administrator login not found

### ISSUE THREAD

**Issue by Michaelr1091** [hashicorp/boundary-reference-architecture#65]

**Comment by Michaelr1091** [comment]
Hi, 
first I say thanks for this document. I succeed install and can access the UI. but I not found for admin login can you help?

thanks

**Comment by Michaelr1091** [comment]
now can I login but limited permission
![image](https://user-images.githubusercontent.com/54924476/146302180-78d67b90-dfda-4262-ae7b-57fde81f691c.png)

**Comment by Michaelr1091** [comment]
Hi @lilic

**Comment by lilic** [comment]
@Michaelr1091 hey, could you detail what deployment and tutorial did you follow?

**Comment by Michaelr1091** [comment]
hi @lilic , I followed this step https://github.com/hashicorp/boundary-reference-architecture/tree/main/deployment/docker

**Comment by jrhrmsll** [comment]
The `admin` password could be found in the logs of the `db-init` container by running something like:

`docker logs compose-db-init-1`

Fragment
```
docker logs compose-db-init-1
Migrations successfully run.
Global-scope KMS keys successfully created.

Initial login role information:
  Name:      Login and Default Grants
  Role ID:   r_bAi1Y83mQk

Initial auth information:
  Auth Method ID:     ampw_GUiwb1T4zN
  Auth Method Name:   Generated global scope initial password auth method
  Login Name:         admin
  Password:           pbtvgBuc4rVwNQnDEJit
  Scope ID:           global
  User ID:            u_MUuwTPeunV
  User Name:          admin
```

**Comment by Michaelr1091** [comment]
cool it's working now. thanks @jrhrmsll
