### ISSUE TITLE
Readme: Example to how to connect ec2 vm and rds 

### ISSUE THREAD

**Issue by nayaksuraj** [hashicorp/boundary-reference-architecture#9]
It will be good if we have any example to connect with following scenario

1. ec2 with ssh password or password less
2. rds

**Comment by malnick** [comment]
Thanks @nayaksuraj - Check out the readme in the deployment sub directory. There's some guidance on how to verify the deployment afterwards: https://github.com/hashicorp/boundary-reference-architecture/tree/main/deployment#verify

The key path can be overridden but defaults to https://github.com/hashicorp/boundary-reference-architecture/blob/main/deployment/aws/vars.tf#L23

Let me know if this helps!

**Comment by malnick** [comment]
For RDS, see the RDS configuration in `deployment/aws/rds.tf` to see the default username and pw used in setting up postgres. 

You should be able to connect over SSH to the private target via Boundary out of the box if the system you're deploying from has your SSH key in the expected place, or you can override that variable to direct it to the right spot. 

In any case, let me know if this answered the question!

**Comment by malnick** [comment]
Closing this out with no response in 7 days.
